LOCAL_TARGET         := $(BUILD_TARGET_DIR)/$(LOCAL_NAME)
LOCAL_INTERMEDIATES  := $(BUILD_INTERMEDIATES_DIR)/$(LOCAL_NAME)
LOCAL_LDFLAGS        += $(addprefix -T, $(LOCAL_LINKER_FILE))
LOCAL_C_SRC          := $(filter %.c, $(LOCAL_SRC))
LOCAL_CXX_SRC        := $(filter %.cpp, $(LOCAL_SRC))
LOCAL_S_SRC          := $(filter %.s, $(LOCAL_SRC))
LOCAL_C_OBJ          := $(addprefix $(LOCAL_INTERMEDIATES)/, $(patsubst %.c, %.o, $(LOCAL_C_SRC)))
LOCAL_CXX_OBJ        := $(addprefix $(LOCAL_INTERMEDIATES)/, $(patsubst %.cpp, %.o, $(LOCAL_CXX_SRC)))
LOCAL_S_OBJ          := $(addprefix $(LOCAL_INTERMEDIATES)/, $(patsubst %.s, %.o, $(LOCAL_S_SRC)))
LOCAL_OBJ            := $(LOCAL_C_OBJ) \
                        $(LOCAL_CXX_OBJ) \
		        $(LOCAL_S_OBJ)
LOCAL_CC             := $(SILENT)$(LOCAL_CROSS_COMPILE)$(CC)
LOCAL_CXX            := $(SILENT)$(LOCAL_CROSS_COMPILE)$(CXX)
LOCAL_LD             := $(SILENT)$(LOCAL_CROSS_COMPILE)$(LD)
LOCAL_AS             := $(SILENT)$(LOCAL_CROSS_COMPILE)$(AS)

$(LOCAL_INTERMEDIATES)/%.o: INTERNAL_TARGET_NAME := $(LOCAL_NAME)
$(LOCAL_INTERMEDIATES)/%.o: %.c
	$(ECHO) "[$(INTERNAL_TARGET_NAME)] CC $(notdir $<)"
	$(MKDIR) $(dir $@)
	$(LOCAL_CC) -c $(LOCAL_CFLAGS) -o $@ $< -MMD

$(LOCAL_INTERMEDIATES)/%.o: INTERNAL_TARGET_NAME := $(LOCAL_NAME)
$(LOCAL_INTERMEDIATES)/%.o: %.cpp
	$(SILENT)$(ECHO) "[$(INTERNAL_TARGET_NAME)] CXX $(notdir $<)"
	$(SILENT)$(MKDIR) $(dir $@)
	$(LOCAL_CXX) -c $(LOCAL_CXXFLAGS) -o $@ $< -MMD

$(LOCAL_INTERMEDIATES)/%.o: INTERNAL_TARGET_NAME := $(LOCAL_NAME)
$(LOCAL_INTERMEDIATES)/%.o: %.s
	$(SILENT)$(ECHO) "[$(INTERNAL_TARGET_NAME)] AS $(notdir $<)"
	$(SILENT)$(MKDIR) $(dir $@)
	$(LOCAL_AS) -c $(LOCAL_ASFLAGS) -o $@ $< -MMD

$(LOCAL_TARGET): INTERNAL_TARGET_NAME := $(LOCAL_NAME)
$(LOCAL_TARGET): $(LOCAL_OBJ)
	$(SILENT)$(ECHO) "[$(INTERNAL_TARGET_NAME)] LD"
	$(SILENT)$(MKDIR) $(dir $@)
	$(LOCAL_LD) -o $@ $^ $(LOCAL_LDFLAGS)

$(LOCAL_NAME): $(LOCAL_TARGET)
.PHONY: $(LOCAL_NAME)

all: $(LOCAL_NAME)

# Include autogenerated dependencies
-include $(patsubst %.o, %.d, $(LOCAL_OBJ))

