name: BuildSystem Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.3
      with:
        release: '9-2020-q2'
    - name: Install bear
      run: sudo apt install bear
    - name: Clean
      run: make -C test/ -j clean
    - name: Run make
      run: make -C test/ -j
    - name: Run binary
      run: ./test/build/targets/test_binary
      env:
        LD_LIBRARY_PATH: "test/build/lib"

  python_lint:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0

